---
title: "R Notebook"
output: html_notebook
---
```{r}
library(pacman)
p_load(ggplot2, usmap, rio)
```
Install packages


```{r}
data <- as.data.frame(income_elec_state)
centers <- as.integer(10)
```
Load data and set quantity of classes

```{r}
head(data)
```
That we have

```{r}
points <- kmeans(data, centers)
```
Clustering data by centers assigned up


```{r}
cluster_data <- cbind(data, cluster = points$cluster)
```
Join class number to data fram

```{r}
head(cluster_data)
```
After clustering

```{r}
centroids <- aggregate(formula=cbind(income, elec) ~ cluster, 
                       data=cluster_data, 
                       FUN=mean)
```
Extract data about centroids of clusters

```{r}
state <- row.names(cluster_data)
```
Extract index states from data frame


```{r}
ggplot(data=cluster_data, aes(x=income, y=elec, colour=factor(cluster))) +
  geom_point(shape=1) +
  geom_text(aes(label = states), hjust=0, vjust=-0.5) +
  geom_point(data = centroids, size=4, shape=8) +
  labs(color="Clusters", x="Income", y="Elec", title="Plot of clustering data")
```
Plot our data

```{r}
usmap_data <- cbind(cluster_data, state)
usmap_data$cluster <- as.factor(usmap_data$cluster)
plot_usmap(regions="states",
           data=as.data.frame(usmap_data),
           values="cluster",
           labels=TRUE) + 
  theme(legend.position="right") +
  labs(title="Clustering data by states"
       )
```

