---
title: "Association Rules"
author: aeroshev
output: html_notebook
---
### Installing Packages 
```{r}
library(pacman)
p_load(arules, arulesViz, ggplot2)
```

### Read list of transactions
```{r}
dataset <- read.transactions("./AssociationRules.csv", sep=" ")
```

## Summary of dataset
### Max quantity
```{r}
summary(size(dataset))
```

### Most popular item
```{r}
itemFrequencyPlot(dataset, topN=10) 
```

## Make association rules
```{r}
rules = apriori(data=dataset, parameter=list(support=0.01, confidence=0)) 
```

### Summary rules
```{r}
summary(rules)
```
```{r}
inspect(rules)
```

### More confidence rules
```{r}
trules <- subset(rules, confidence >= 0.5)
```
```{r}
summary(trules)
```
```{r}
inspect(trules)
```



```{r}
# Some 10 sample
top_rules <- sample(rules, 10)
# High confidence rules
rules_conf <- sort(rules, by="confidence", decreasing=TRUE)
# High lift rules
rules_lift <- sort(rules, by="lift", decreasing=TRUE)
# Top 10 rules by confidence
top_rules_conf <- head(rules_conf, n=10)
# Top 10 rules by lift
top_rules_lift = head(rules_lift, n=10)
```


### Plot of all finded rules
```{r}
plot(rules, 
     method="scatterplot", 
     measure=c("support", "confidence"), 
     shading="lift",
     jitter=0.2
)
```

### Plot of hight confidence rules
```{r}
plot(trules, 
     method="scatterplot", 
     measure=c("support", "confidence"), 
     shading="lift",
     jitter=0.2
)
```

### Compare support and lift
```{r}
plot(rules, 
     method="scatterplot", 
     measure=c("support", "lift"), 
     shading="confidence",
     jitter=0.2
)
```
```{r}
plot(trules, 
     method="scatterplot", 
     measure=c("support", "lift"), 
     shading="confidence",
     jitter=0.2
)
```
```{r}
head(quality(trules))
```



```{r}
plot(associa_rules, 
     method="scatterplot", 
     measure=c("support", "confidence"), 
     shading="lift",
     engine="htmlwidget"
)
```
```{r}
plot(associa_rules, 
     method="scatterplot", 
     measure=c("support", "lift"), 
     shading="confidence",
     engine="htmlwidget"
)
```

```{r}
plot(top_rules_conf, method="paracoord")
```

```{r}
plot(top_rules_lift, method="paracoord")
```

```{r}
plot(top_rules_conf, method="matrix", measure="confidence")
```
Matrix based plot

```{r}
plot(top_rules_lift, method="matrix", measure="lift")
```

```{r}
plot(top_rules_lift, method="grouped")
```

```{r}
plot(top_rules_conf, method="graph",  engine="htmlwidget")
```
```{r}
top_3_lift = head(top_rules_lift, n=3)

plot(top_3_lift, method="graph")
```

```{r}
hight_trustly_rules <- subset(associa_rules, confidence > 0.8)

first_38_conf = head(sort(hight_trustly_rules, by="confidence", decreasing=TRUE), n=38)

plot(first_38_conf, 
     method="matrix", 
     shading=c("lift", "confidence"), 
     measure=c("lift", "confidence"), 
     control=list(reorder=FALSE)
)
```






